### PR TITLE
Extract CLI code to separate package

### PR DESCRIPTION
**Pull request by syndbg**
Makes programmatic usage of consul-template
much easier without having to duplicate CLI code

### CODE REVIEW

**Comment by syndbg** [comment]
Ping anyone? Perhaps @pearkes :)

**Comment by syndbg** [comment]
Ping. Ping.

Any interest in merging this? :)

**Comment by pearkes** [comment]
Thanks for the PR @syndbg -- I don't think we'll be able to take a look at this too soon given work going on elsewhere in Consul, but we can certainly leave it open until someone is able to invest time in taking a look!

**Comment by eikenb** [comment]
Hey @syndbg. I'm reviewing all the community PRs for inclusion in 0.22.0 and find this one interesting. I'm thinking about converting much of CT more into a library with front ends for consul template and envconsul, and this looks to be a step toward that. Any interest in rebasing/updating this PR for current master. Things have drifted a bit since you did this. Thanks.

**Comment by syndbg** [comment]
Yes, sure.

**Comment by eikenb** [comment]
Hey @syndbg,

Thanks for all the work you did on this but it looks like we're going a different route. We're going to be refactoring out all the core "library-worthy" functionality into a separate module.

Do you use it as a library? We have an internal document on the API for the library that we're using for discussion and I might be able to get you a copy (or at least cut-n-paste the api spec out) for review. I'm getting feedback from internal library users (both vault and nomad use consul-template as a library) but would love to get additional feedback from community members using it as a library.

Anyways. That work would seem to make this PR no longer useful and I was going to close it. I'll wait for a response first (as I tend to miss comments on closed items).

Thanks for the time and work you put in on this.

**Comment by syndbg** [comment]
> Thanks for all the work you did on this but it looks like we're going a different route. We're going to be refactoring out all the core "library-worthy" functionality into a separate module.

Sounds good.

> Do you use it as a library? We have an internal document on the API for the library that we're using for discussion and I might be able to get you a copy (or at least cut-n-paste the api spec out) for review. I'm getting feedback from internal library users (both vault and nomad use consul-template as a library) but would love to get additional feedback from community members using it as a library.

We're using it as a library, but it's a very blackbox approach. We use the `cli` pkg to apply opinionated usage of `consul-template`.

We don't try to extend template functionality, re-use template functions, etc.


E.g production snippet

```
import (
	"flag"
	"io"
	"io/ioutil"

	"github.com/sumup-oss/go-pkgs/logger"
	"github.com/syndbg/consul-template/cli"
)

func RunConsulTemplateCLI(args []string, stdout, stderr io.Writer, consulTemplateConfigFilePath string) int {
        .......
	consulTemplateCLIinstance := cli.NewCLI(stdout, stderr)
	args = append(args, "-config", consulTemplateConfigFilePath)
	return consulTemplateCLIinstance.Run(args)
}
```

**Comment by eikenb** [comment]
Hey @syndbg, thanks for the feedback and if you want to look at it the library I'm working on is public and can be found at https://github.com/hashicorp/hcat.

It is unreleased and still under heavy development but is coming along. We already use it in another project that is released, so it is working but will still undergo some significant changes. That is you might be interested in taking a look to see how it might fit your use case and submit any feature requests/issues you might have.

I created an issue there referring to your comments here so I wouldn't forget about this case.

https://github.com/hashicorp/hcat/issues/49

Thanks again.

**Pull request closed without merging**
