### PR TITLE
Upgrade go modules to version which has CVE fixes

### LINKED ISSUE #1614: trivy scanner is reporting CVEs
### Expected behavior

What should have happened?

Should not have had any CVEs

### Actual behavior

Found CVEs

Screenshot 2022-08-08 at 12 01 18 PM

What actually happened?

### Steps to reproduce

1. trivy image --security-checks vuln hashicorp/consul-template:0.29.1

### PR DESCRIPTION
**Pull request by noorul**
Fixes #1614

### CODE REVIEW

**Comment by eikenb** [comment]
Hey @noorul, thanks for the issue and PR!

Dependabot is supposed to pick these things up... not sure why it missed this one. Thanks for reporting/fixing it.

That failure is due to a changed error message in the latest consul release. If you wouldn't mind rebasing on HEAD and re-pushing this it should fix that and allow the CI testing to pass.

**Comment by noorul** [comment]
@eikenb rebased

**Comment by eikenb** [comment]
Thanks @noorul!

**Comment by noorul** [comment]
@eikenb Is CLA required for merge?

**Comment by eikenb** [comment]
@noorul ..
> @eikenb Is CLA required for merge?

Yes. I'm afraid it's required by my company.

**Comment by eikenb** [comment]
> Dependabot is supposed to pick these things up... not sure why it missed this one. Thanks for reporting/fixing it.

I see why dependabot didn't pick it up... I haven't enabled dependabot in this repo yet. :facepalm:

**Comment by noorul** [comment]
@eikenb Can you enable dependabot? I will be happy to discard this patch as I need to do some paper work to sign CLA.

**Comment by eikenb** [comment]
I'll be happy to do that @noorul, I just like to use contributors submissions whenever possible. I'll work on getting dependabot enabled and making sure everything is up to date and happy. If you'd like to go that way please close this PR but leave the issue open. I should be able to mark it resolved in the Dependabot PR.

Thanks!

**Comment by eikenb** [comment]
I have dependabot doing it's thing and am pretty sure I got this fixed with #1622. I'm still working on a few other dependabot updates but I'm going to go ahead and close this. Thanks again!

**Comment by noorul** [comment]
@eikenb Great! Thank you!

**Comment by noorul** [comment]
@eikenb Can we make a release?

**Pull request closed without merging**
