### PR TITLE
consul namespaces support

### PR DESCRIPTION
**Pull request by eikenb**
Add support for Consul namespaces following the same pattern as for
Vault namespaces.

Depends on code in consul's master branch (unreleased). So won't build unless you update the modules dependencies to the correct master commit. Once the upstream code is released, the module dependencies will be updated and added to this PR.

### CODE REVIEW

**Comment by lornasong** [comment]
This makes sense to me! I can see the new Consul namespaces' parallel with Vault's. Can approve after module dependencies are updated or happy to approve now - whatever the team norm is.

**Comment by eikenb** [comment]
Thanks @lornasong! I think it could be approved now and if anything but the dependencies change I could ping for another look.

**Comment by freddygv** [comment]
Hi @eikenb, one thing to consider for long-run namespace support is that users may want to query more than one namespace across different template functions.

This ie because:
- Some endpoints allow using the wildcard namespace `'*'` (list methods), while others do not (set, get delete methods).
- Some resources like nodes are only in the default namespace while resources like services/checks/KV can be in user-created namespaces.

If someone wants to use multiple namespaces, I think we would need to enable something like we do for querying nodes:
https://github.com/hashicorp/consul-template#nodes

This way someone can pick a default namespace for their queries in the config, but also overwrite the query options for a particular request. 

For example: If someone wants to query services within the `billing` namespace but also nodes in the default namespace. They could set `billing` as the namespace in the config, and then override the namespace in the `nodes` template function.

**Comment by eikenb** [comment]
Hey @freddygv, thanks for the input.

I thought of that and other possible enhancements but decided there was no good way to know which would be useful at this point. So I thought it better to keep it as simple as possible at this point and see what kind of feature requests come in.

**Comment by eikenb** [comment]
Rebased on newer consul-api so it now passes CI.

**Pull request merged**
