### PR TITLE
Fixed typo and added example to README

### PR DESCRIPTION
**Pull request by MrWong99**

### CODE REVIEW

**Comment by eikenb** [comment]
Hey @MrWong99, thanks for submitting this and sorry for the long delay in responding.

The documentation has been reorganized a bit and the PR needs updating. 
Would like to update your PR to fix the docs in their new location? If not, I'll be happy to do it but thought you might want to. Either way thanks for pointing this out.

**Comment by MrWong99** [comment]
> Hey @MrWong99, thanks for submitting this and sorry for the long delay in responding.
> 
> The documentation has been reorganized a bit and the PR needs updating.
> Would like to update your PR to fix the docs in their new location? If not, I'll be happy to do it but thought you might want to. Either way thanks for pointing this out.

Hi @eikenb, I am working on it 👍

**Comment by MrWong99** [comment]
Done :)

Sorry for the little messy commit history, since I made the changes in the GitHub UI and not locally... Feel free to squash the pull request during merge or if you want to I can redo it later when I am back home.

**Comment by eikenb** [comment]
Thanks for the updates!

No worries about the history. I'll use the "Squash and merge" option for the PR, keeping the message from your original commit.

**Comment by eikenb** [comment]
I ended up tweaking the commit message... but it is basically the same.

**Pull request merged**
