### PR TITLE
Record templates that would have rendered separate from those that did

### PR DESCRIPTION
**Pull request by sethvargo**
Fixes https://github.com/hashicorp/consul-template/issues/188

/cc @ryanuber @armon

### CODE REVIEW

**Comment by armon** [comment]
LGTM

**Comment by ryanuber** [comment]
@sethvargo LGTM. Is there any way to test the functionality, e.g., run in once mode against a template path which already has the most up-to-date content, ensure we don't hang and no commands run? Not sure if we have some helpers to make that easy or not.

**Comment by sethvargo** [comment]
@ryanuber I started writing that test, but it was really fragile. I'll see what I can come up with.

**Comment by sethvargo** [comment]
@ryanuber okay, I added a test.

**Pull request merged**
