### PR TITLE
Windows SC Service

### PR DESCRIPTION
**Pull request by Vulfox**
This allows consul-template to be ran via Windows SC (Service Control) without the need of using nssm.exe.

The code is copy/paste from how consul and nomad implements the same feature.

### CODE REVIEW

**Comment by MrWong99** [comment]
Ran into the issue today when trying to setup a service, fix would be much appreciated 👍

**Comment by MrWong99** [comment]
Btw I successfully tested this enhancement on Windows 10 with v0.25.0 and only this PR merged.

**Comment by eikenb** [comment]
Hey @Vulfox, thanks for taking the time to put together this PR.

Sorry for the long delay in responding, we've been very busy with other projects and haven't had time to review the enhancement contribution in a while. I'm hoping to make some time in the near-ish future to review all the enhancement PRs and put out a release for them. Thank you for your patience.

**Comment by ksandrmatveyev** [comment]
Hi,

Any updates on this?

**Comment by eikenb** [comment]
Hey @ksandrmatveyev,

I'm so sorry that the delays keep coming, I feel like I've let the community down on many of these issues. Things are looking up though. We finally released the initial GA version of our other big project and I've got permission to switch back to working on this as soon as I finish up with a couple bugs that came up with that release. 

So while it seems like I'm saying near the same thing again, this time I know I'll be back.

Please :+1: on the original post if you would, we use the reactions as a way of prioritizing.

Thanks.

**Comment by eikenb** [comment]
This has been merged. Did it locally due to conflict issues and github didn't pick up on the fact that I merged it.

**Comment by Vulfox** [comment]
Thank you @eikenb !! I am a little sad it didn't make it to its birthday, but I am more glad it is merged!

**Pull request closed without merging**
