### PR TITLE
General Map structure for returning values from define. 

### PR DESCRIPTION
**Pull request by ewah**
Add support for creating a struct in a template #760

### CODE REVIEW

**Comment by bitsofinfo** [comment]
Nice!

**Comment by bitsofinfo** [comment]
#780

**Comment by ewah** [comment]
Wondering what the future of this PR will be? 

We're about to push this into an integration testing arena.  And would prefer to know if the direction will go this way or towards something like Scratch (#780).

From a quick look, Scratch adds an "Add()" method and does some stricter logging than my Map.  My Map has a few more method implemented (containsKey and containsValue I really would like to have in play)

**Comment by jippi** [comment]
the indentation is way off? :)

**Comment by bitsofinfo** [comment]
No discussion on this PR vs Scratch??

**Pull request closed without merging**
