### PR TITLE
Allow colons in the template command on the command line

### PR DESCRIPTION
**Pull request by tanner-bruce**
This allows you to write something like:

```shell
consul-template -template "in.ctmpl:out:curl https://google.com:443"
```

### CODE REVIEW

**Comment by sethvargo** [comment]
Can you add a test for this? You can also see that it's failing some windows-specific tests (which is why the behavior is defined like it is).

**Comment by tanner-bruce** [comment]
@sethvargo working on it, had trouble running tests locally so I wanted to get the travis output. This is my `make test` output if you are willing to take a look: https://gist.github.com/tanner-bruce/43a5b168315a34f4f5eddd2fce9caeb7

**Comment by sethvargo** [comment]
Do you have consul installed and compiled on your path?

**Comment by tanner-bruce** [comment]
@sethvargo thanks! That was it.

**Pull request merged**
