### PR TITLE
Added jq to be installed in the docker image

### PR DESCRIPTION
**Pull request by Gaardsholt**
Small change, just think that it would be great to have jq installed

### CODE REVIEW

**Comment by greut** [comment]
you probably ain't gonna need it.

**Comment by Gaardsholt** [comment]
@greut I need it ;)

**Comment by greut** [comment]
then, it's probably easier to derive and host your own image.

**Comment by Gaardsholt** [comment]
@hashicorp-cla I have signed the CLA - same day as I created the pull request

**Comment by eikenb** [comment]
Hey @Gaardsholt, thanks for taking the time to submit this.

I'd prefer to keep the docker images restricted in scope to contain only what is absolutely necessary to run CT. This makes the base image smaller and simpler to work with while also making it less burdensome when someone, like in your case, wants to customize them as they aren't already bloated with a bunch of stuff they don't need.

In fact this reminds me I need to review what is in the existing images as I think they already have a couple unnecessary things installed.

**Pull request closed without merging**
