### PR TITLE
Integrate panel

### PR DESCRIPTION
**Pull request by Celebrum**

### CODE REVIEW

**Comment by Celebrum** [comment]
/review
auto_approve
--pr_reviewer.extra_instructions="
Additional instructions:
- 
"
--pr_reviewer.inline_code_comments=true
-i
--pr_reviewer.require_score_review=true
--pr_reviewer.require_can_be_split_review=true
--pr_reviewer.require_soc2_ticket=true
--pr_reviewer.num_code_suggestions="8"

**Comment by Celebrum** [comment]
I have signed the agreement.
SeCuReDmE

**Comment by schmichael** [comment]
Locking as this is at best misguided AI slop, at worst an attempt to inject malicious code via third party imports.

**Comment by crw** [comment]
As the Community representative, I agree with the above assessment. 

In any case, any integration of this scope would need to be assessed and sponsored by our Partnerships team, please see https://www.hashicorp.com/partners.

**Pull request closed without merging**
