### PR TITLE
Writer to log date / time in conistent format like in other places.

### PR DESCRIPTION
**Pull request by aphorise**
Related to: [Vault 9816](https://github.com/hashicorp/vault/issues/9816) - where dates do not appear in an inconsistent manner.

### CODE REVIEW

**Comment by eikenb** [comment]
Hey @aphorise, thanks for the PR and sorry for the delayed feedback.

It appears this is attempted to match consul-template's log output format to Vaults. This is indirectly in our plans, as we plan to switch to go-hclog when we have a chance (vault uses it's default format), but this I think helps in the mean time. Thanks.

**Comment by calvn** [comment]
@eikenb should this be tagged for `0.25.2`/`0.26.0`? ` 0.25.1` seems to be an existing release from July

**Comment by eikenb** [comment]
@calvn Thanks!

**Comment by mladlow** [comment]
@eikenb - I'm not sure of the release cadence for consul-template. Did 0.25.2 get released?

**Comment by eikenb** [comment]
No @mladlow, I'm sorry it hasn't been released yet. The team got sidetracked kicking off a new project which distracted us from our other projects for a time. After the holiday break we will be freeing up some time for this and will get a release out at that time. Sorry for the delay and lack of attention here. We are aware and are working to get things back in order and just beg for patience.

Thanks

**Comment by mladlow** [comment]
No worries - just looking for clarity!

**Pull request merged**
