### PR TITLE
add weights field for HealthService

### PR DESCRIPTION
**Pull request by fengxuway**
resolve Issue #1287

### CODE REVIEW

**Comment by fengxuway** [comment]
maybe the test code need change.

**Comment by phamtai97** [comment]
Can I ask if the PR has been tested and merged yet?

**Comment by fengxuway** [comment]
@phamtai97 Yes. But the test code need compare expected values, so I have to change test code to add `Weights` field.

See here please:  <https://github.com/fengxuway/consul-template/commit/20512ea548236838450cc142d94630aa0850faca?diff=split>

**Comment by eikenb** [comment]
I'm going to merge this for 0.25.0 but I'd like the field to be a value, not a pointer. I can make this change post merge but if you get a chance to update the PR, please do.

That is change `Weights *api.AgentWeights` to `Weights api.AgentWeights` along with the other required changes.

Thanks.

**Comment by pierresouchay** [comment]
As a side note, if the value is not set (aka not present on Consul side (ie: à Consul agent pre version 1.0.7 IIRC), the value is expected to be passing:1 and warning:1 (that's the value on Consul side when, for instance DNS retrieve it)

**Comment by eikenb** [comment]
The conflict is due to formatting. Between that, a new test that was added and needs the Weights and changing it from a pointer to a value... Unless you speak up @fengxuway, I'm just going to pull this down, fix it up and merge from there. I'll be sure to keep attribution on the changes.

**Comment by eikenb** [comment]
Merged via local checkout.

**Pull request closed without merging**
