### PR TITLE
Add transport section to configuration file

### PR DESCRIPTION
**Pull request by shokerplz**
Add transport section to configuration file documentation.
This is not the best version of docs on transport section so I am open for any advices. But I personally do really want to see transport section documentation at least for dial_timeout, which is really important in some situations.

### CODE REVIEW

**Comment by eikenb** [comment]
Hey @shokerplz, thanks for the PR! Documentation fixes are always welcome.

But... I'm sorry to say I can't merge it until you sign the CLA. Thanks.

**Comment by shokerplz** [comment]
> Hey @shokerplz, thanks for the PR! Documentation fixes are always welcome.
> 
> But... I'm sorry to say I can't merge it until you sign the CLA. Thanks.

I signed it, I don't know why it says that I didn't on github. Here's how I see the page about signing 
image

**Comment by eikenb** [comment]
Maybe it is complaining due to the AUTHOR email signature on the git commit doesn't match the email address you have registered with github? That is how I interpret that text around the CLA signature detector.

> Ivan Kovalev seems not to be a GitHub user.
> You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by shokerplz** [comment]
> Maybe it is complaining due to the AUTHOR email signature on the git commit doesn't match the email address you have registered with github? That is how I interpret that text around the CLA signature detector.
> 
> > Ivan Kovalev seems not to be a GitHub user.
> > You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

Yeah you are right, I missed this message somehow

**Comment by eikenb** [comment]
Great, thanks!

**Pull request merged**
