### PR TITLE
Adds support for service tagged addresses

### LINKED ISSUE #1398: [Feature] Add support for ServiceTaggedAddresses
I need to access the values published by a service in its `ServiceTaggedAddresses` field. I can see the value by querying consul API directly, but they are not available in consul-template.
If I understood the code correctly that is because `ServiceTaggedAddresses` is not parsed into the CatalogService struct in
https://github.com/hashicorp/consul-template/blob/master/dependency/catalog_service.go

Would you be interested in a PR to add that?

### PR DESCRIPTION
**Pull request by danieleva**
Resolves #1398

### CODE REVIEW

**Comment by eikenb** [comment]
Hey @danieleva,

I wanted to let you know that I'm not just ignoring this. I'm currently reworking the dependency code and am delaying merging this until I figure some things out.

Thanks for the PR and I will look more closely into merging it once I've got past these issues.

**Comment by danieleva** [comment]
No worries, thanks for the feedback. I appreciate your effort in maintaining this awesome tool 👍 🙇

**Comment by fernandino143** [comment]
This is great. Wish it was merged 🥇

**Comment by eikenb** [comment]
I do apologize for the long delay on this. A new project my team started really took off internally and became our top priority all the sudden and we've been mostly heads down on it since. It will be going into beta/ga in month or so and we definitely plan to give these other projects much more attention once we reach that milestone.

Thank you for your patience.

**Pull request merged**
