### PR TITLE
Add support for tagged addrs and node meta everywhere

### PR DESCRIPTION
**Pull request by sethvargo**

### CODE REVIEW

**Comment by sethvargo** [comment]
Hmmm... these tests are all passing locally

**Comment by MiLk** [comment]
What's the status on this? I would like to start using the node meta data from consul-template.

**Comment by sethvargo** [comment]
Hi @MiLk 

As you can see, the tests are failing. I haven't had time to dig into why. If you want to use this, you can build from this branch, but it might have bugs

**Comment by MiLk** [comment]
I've been able to build and run the tests on OSX with go 1.7.5 without any failure.
I will try again on one server with Ubuntu 16.04.
At first glance, I don't see why it's failing on travis.

**Comment by sethvargo** [comment]
@MiLk same. Works fine locally, but sad on Travis. If you figure it out - let me know. I spent about 4 hours before I had to move on 😦

**Comment by MiLk** [comment]
Tests are fine on my server with Ubuntu 16.04 using the same go version Travis is installing.
I will try to reproduce the Travis environment with http://stackoverflow.com/questions/29753560/how-to-reproduce-a-travis-ci-build-environment-for-debugging.

**Comment by MiLk** [comment]
It seems Travis doesn't allow to listen on/close connections to ports fast enough for the tests to work.
See #876

**Comment by MiLk** [comment]
You probably need to run only `make test-race` and not `make test test-race`, I think that's why the other tests are failing.

**Pull request merged**
