### PR TITLE
Switch to using Go11Modules

### PR DESCRIPTION
**Pull request by prologic**

### CODE REVIEW

**Comment by greut** [comment]
You'll probably need #1230 (see #1208). I tend to like having the vendors versioned as well via `go mod vendor`, `go build -mod=vendor`

**Comment by prologic** [comment]
Is there really a point in committing the source code to dependencies today? `go mod` makes all this painless and trivial to manage dependencies without polluting your source tree IHMO.

**Comment by jefferai** [comment]
Duplicate of #1208

**Comment by greut** [comment]
@prologic Agreed, until something gets deleted by someone else. https://status.npmjs.org/incidents/41zfb8qpvrdj

**Pull request closed without merging**
