### PR TITLE
Quiesce on a per-template basis

### LINKED ISSUE #154: Quiescence should be per-template
Right now, quiescence is calculated globally for the runner, but it should really be on a per-template basis.

### PR DESCRIPTION
**Pull request by sethvargo**
Fixes #154

### CODE REVIEW

**Comment by mitchellh** [comment]
So far so good to me. Only thing I don't see: is there any way a template is deregistered, and if so, we should remove it from the quiescence map.

**Comment by sethvargo** [comment]
@mitchellh that's not something that is currently possible (directly). When we reload configuration, we make all new template objects, so the problem should be avoided.

**Comment by mitchellh** [comment]
Right, but it looks like we tie the path directly into this map which is part of runner. Or do we create a new runner, too?

**Comment by sethvargo** [comment]
@mitchellh we [create an entirely new runner object](https://github.com/hashicorp/consul-template/blob/master/cli.go#L148-L154)

**Comment by mitchellh** [comment]
Then :+1:

**Pull request merged**
