### PR TITLE
Added function regexMatch to test values against a regular expression

### PR DESCRIPTION
**Pull request by split3**
Allows checking string values against a regular expression.

### CODE REVIEW

**Comment by sethvargo** [comment]
Hey @split3 

This looks really good! Do you think you could add this function to the `TestExecute_renders` function too please? It would be awesome if you could update the README with this example. All the APIs are documented in alphabetical order.

**Comment by split3** [comment]
@sethvargo Absolutely will do

**Comment by split3** [comment]
Requested changes added

**Comment by split3** [comment]
Hey @sethvargo 

Is there anything else missing that needs to be added to get this merged?

**Comment by sethvargo** [comment]
Looks great, thanks!

**Pull request merged**
